# Generated by Django 4.0.4 on 2022-05-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(auto_now_add=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Episodio',
                'verbose_name_plural': 'Episodi',
            },
        ),
        migrations.CreateModel(
            name='Videogame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(auto_now_add=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Videogame',
                'verbose_name_plural': 'Videogame',
            },
        ),
    ]
