# Generated by Django 4.0.4 on 2022-05-07 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backoffice', '0002_reset_modelli'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(auto_now_add=True)),
                ('ts', models.DateTimeField(auto_now=True)),
                ('titolo', models.CharField(default='', max_length=256, verbose_name='Titolo')),
                ('episodio_numero', models.CharField(blank=True, max_length=32, null=True, verbose_name='Numero')),
                ('data_uscita', models.DateField(default=datetime.date(2019, 12, 15), verbose_name='Data uscita')),
                ('durata', models.DurationField(default=datetime.timedelta(seconds=1800), verbose_name='Durata')),
            ],
            options={
                'verbose_name': 'Episodio',
                'verbose_name_plural': 'Episodi',
            },
        ),
    ]
