# Generated by Django 4.0.4 on 2022-05-08 09:37

import backoffice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_model_episodio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episodio',
            options={'verbose_name': 'episodio', 'verbose_name_plural': 'episodi'},
        ),
        migrations.AddField(
            model_name='episodio',
            name='cover',
            field=models.ImageField(blank=True, help_text="Cover dell'episodio. ATTENZIONE: l'immagine deve essere caricata in formato\n                     PNG e dimensione 256x256px, non viene fatto il resize.", null=True, upload_to=backoffice.models.user_directory_path, verbose_name='Cover'),
        ),
        migrations.AddField(
            model_name='episodio',
            name='url',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='URL'),
        ),
    ]
