# Generated by Django 4.0.4 on 2022-05-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_aggiunti_url_e_cover_all_episodio'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='url_video',
            field=models.URLField(blank=True, help_text="URL al contenuto video dell'episodio. Opzionale.", max_length=256, null=True, verbose_name='URL video'),
        ),
    ]
