# Generated by Django 4.0.4 on 2022-05-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_episodio_url_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='url_post',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name="URL del post che annuncia l'episodio"),
        ),
        migrations.AlterField(
            model_name='episodio',
            name='url',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name="URL dell'episodio in formato audio"),
        ),
    ]
