# Generated by Django 4.0.4 on 2022-05-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0008_videogame_ordinati_per_titolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='note',
            field=models.TextField(blank=True, help_text='Note per i redattori, non vengono visualizzate in alcun punto del sito', null=True, verbose_name='Note libere'),
        ),
    ]
