# Generated by Django 4.1 on 2022-10-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0012_indice_trigrammi_titolo_videogame"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodio",
            name="pubblicato",
            field=models.BooleanField(default=False, verbose_name="Pubblicato"),
        ),
    ]
