# Generated by Django 4.1.3 on 2022-11-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0014_episodi_esistenti_tutti_pubblicati"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordMessage",
            fields=[
                ("id", models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name="ID")),
                ("ts", models.DateTimeField(verbose_name="Timestamp del messaggio")),
                ("author_avatar", models.URLField(max_length=256, verbose_name="URL avatar autore")),
                ("author_name", models.CharField(max_length=256, verbose_name="Nome autore")),
                ("content", models.TextField(verbose_name="Contenuto")),
                ("consiglio", models.BooleanField(default=False, verbose_name="È un consiglio")),
            ],
            options={
                "verbose_name": "messaggio Discord",
                "verbose_name_plural": "messaggi Discord",
            },
        ),
    ]
